version: '3.8'

services:
  
  frontend:
    container_name: noteaifrontend
    image: noteainext-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
    env_file: ".env"
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: true
      MONGO_URL: ${DATABASE_URL}
      DB_NAME: noteaidb
      COL_NAME: noteai
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata6: