version: '3.8'

services:
  
  frontend:
    container_name: noteaifrontend
    image: noteainext-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: true
      MONGO_URL: mongodb://mongo:27017
      DB_NAME: noteaidb
      COL_NAME: noteai
    command: npm run dev
    networks:
      - app-network
  
  mongo:
    image: mongo:7.0.10-rc0-jammy
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata6: