name: NoteAI App on Github Pages

on:
  push:
    branches:
      - main  # Deploy when pushing to the main branch
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: self-hosted
    environment: Production
    strategy:
      matrix:
        node-version: [16.20.2]

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}
      NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: ${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL }}
      NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: ${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      PINECONE API KEY: ${{ secrets.PINECONE_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Set Secrets and Change Dir
        run: |
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> .env.production
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> .env
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}" >> .env.production
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}" >> .env
          echo "CLERK_SECRET_KEY=${{secrets.CLERK_SECRET_KEY}}" >> .env.production
          echo "CLERK_SECRET_KEY=${{secrets.CLERK_SECRET_KEY}}" >> .env
          echo "NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL}}" >> .env.production
          echo "NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL}}" >> .env
          echo "NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL}}" >> .env.production
          echo "NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL}}" >> .env
          echo "NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=${{secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL}}" >> .env.production
          echo "NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=${{secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL}}" >> .env
          echo "NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=${{secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL}}" >> .env.production
          echo "NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=${{secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL}}" >> .env
          echo "OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}" >> .env.production
          echo "OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}" >> .env
          echo "PINECONE_API_KEY=${{secrets.PINECONE_API_KEY}}" >> .env.production
          echo "PINECONE_API_KEY=${{secrets.PINECONE_API_KEY}}" >> .env
      - run: pm2 restart 1

